### ISSUE TITLE
Consortium map

### ISSUE THREAD

**Issue by azzaea** [h3abionet/node-accreditation#1]
Probably this code helps? A vanilla consortium map:
```
if (!require('tidyverse'))
  install.packages(tidyverse)
if(!require('maps'))
  install.packages(maps)


mapWorld <- map_data('world') %>%
  mutate(Countries = 'world') %>%
  filter(!str_detect(region, "Antarctica"))
bordersWorld <- borders('world', colour="gray50") # create a layer of borders

consort <- c('Morocco', 'Tunisia','Egypt', 'Sudan','Mali', 'Senegal',
             'Nigeria', 'Ghana', 'Uganda', 'Kenya', 'Tanzania', 'Botswana', 'Malawi', 'Zimbabwe',
             'South Africa', "Mauritius")
mapConsortia <- map_data("world", regions = consort) %>%
  mutate(Countries = 'H3ABioNet Consortium')

ggplot() + 
  geom_polygon(data = mapWorld, aes(x=long, y=lat, group=group), fill = 'seashell1', 
               color = 'gray50') +
  geom_polygon(data = mapConsortia, aes(x=long, y=lat, group=group, fill = Countries),  
               alpha = 1, color = 'gray50') + coord_cartesian(xlim = c(-25, 60), ylim = c(-40, 50)) +
  theme(axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(),
        legend.position = "bottom", panel.grid = element_blank())  
 
```
The result is something like below, that can then be annotated with any extra info, or trimmed as necessary
![image](https://user-images.githubusercontent.com/11329665/62014997-e7e96c00-b1a7-11e9-97f3-2a76ed45b83e.png)

**Comment by cjfields** [comment]
Hi @azzaea I added code (finally!).  Several interesting suggestions and additions; one key issue with the above map was a bit of potential sensitivity regarding the borders of Morocco (only map I could find that has workaround was Google).

**Comment by azzaea** [comment]
Nice! Good catch about Morocco.
I recall struggling with the Google map before (something like the download limit, my IP or relevant issue- don't really recall),  hence the above was a workaround (the rest of the map might have issues too- countries and borders are quite dynamic!!)!
I'm closing this now :)

**Comment by cjfields** [comment]
@azzaea there is a API time limit for the free trial period, I just re-upped mine which fixed the issue. And Sumir alerted me to Morocco, have him to thank :)
